services:
  database:
    image: 'postgres:17'
    container_name: bytegem_db
    ports:
      - 5432:5432
    
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:Z
    
    environment:
      POSTGRES_USER: bytegem # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: bytegem # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: bytegem # The PostgreSQL default database (automatically created at first launch)